services:
- docker

env:
  global:
  - secure: FSQZIVgPk/IKVQbNqdly9hYkuvSxzgp7I4u9y7zddPqufrX01Q+t5hdmvWIcpGl7ZagrgrG0tiqaIead+2y3ZTZ2PdxJ/cduXxx01XcRESxHte9m+CuAVlRXuL1rpaQBhutPqScQI5/xhPsBUrJ4oVLEjgzbqB20Yu2eOwrphWSpxu7B2O9e5mQsIr6TrDZOjt0/ZLtt/5/Soh+9yPuO40YzUdqglwWjkxbogn2GDF2wwPi2tv+33wEPQtaOLU83EJQuDuEA8Gk9arV/G+di004ABYXhMgdg6jT77omhyNRQE0nqdjd1raLq1GSm0FaFg5ZB6O+GC9D6yFTNzfmyOCvKDNBtfgCbr/dgeW4Nsk0wpPohWMDBr38Hk+I9aEGZ5JAR3qqZq7AU+5Nw9Fge6R0NEFA0EsCMjs64JKjD4NG9TCAwPDsfPX9t8My6Z0vNGnAGUvY8FxJ5ryIWUG28D5Pc04HhtpGk5RBDhNFw+YioStmcSbQUakUvI+tNKnzeGHl7o2Ydeha58zuHmlka9250Ja3tXa3fXLATA4SYJaauipMtjNfo8Wt3h5cnk0auea70uX8jikD6bdnEulZke4fdLPaBbjRH8LxZbmoHUYtdFJiYunrmrB82sGEhHXpeJc81sqJtfEk9tKwFRBc4dqGNkxqYFXjt33I/xKsvZps=

matrix:
  include:
  # hola-mundo-api
  - name: hola-mundo-api pipeline
    language: node_js
    node_js:
    - 12
    env:
    - PACKAGE_LOCATION=hola-mundo-api
    - HEROKU_APP_NAME=hola-mundo-api-dev
    - HEROKU_PROC_NAME=web
    - ECS_REPO=805382315593.dkr.ecr.us-east-1.amazonaws.com/api-default
    - PROVIDER=heroku
    before_script:
    - cd $PACKAGE_LOCATION   
    script:
      - docker build -t ${PACKAGE_LOCATION}:test --target test .

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./.ci/deploy.sh
  on:
    branch: master
